/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.Doc;
import Control.DocControler;
import java.util.ArrayList;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.plaf.DimensionUIResource;
import javax.swing.table.DefaultTableModel;

import org.w3c.dom.events.Event;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


/**
 *
 * @author leanddro
 */
public class TabelaDados extends javax.swing.JFrame {
    /**
     * Creates new form TabelaDados
     */
    public TabelaDados() {
        initComponents();
        tabela_default = DocControler.getArrayDocs() ;
        exibirTabela(tabela_default);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private ArrayList<Doc> tabela_default;
    private ArrayList<Doc> tabela;
    private void exibirTabela(ArrayList<Doc> tabela_){
        tabela = tabela_;
        DefaultTableModel tabela_modelo = (DefaultTableModel)jTable1.getModel();
        tabela_modelo.setRowCount(0);
        
        for(Doc dados : tabela_){
            tabela_modelo.addRow(new Object[]{
                dados.getId(),
                dados.getAno(),
                dados.getDocumento(),
                dados.getAtoNormativo(),
                dados.getEmenta(),
                dados.getLink(),
                dados.getStatus()
            });
        }
        jTable1.setModel(tabela_modelo);
    }
    
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txEntrada = new javax.swing.JTextField();
        txEntrada.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        		if(e.getKeyCode()==10){
                    exibirTabela(pesquisar());
                }
        	}
        });
        btnBuscar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnApagar.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
                DocControler.deletar();
                exibirTabela(DocControler.getArrayDocs());
        	}
        });
        btnCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "","ANO", "DOCUMENTO", "ATO NORMATIVO", "EMENTA", "LINK", "STATUS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.getColumnModel().getColumn(0).setWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.setDefaultEditor(Object.class,null);
        // jTable1.getColumnModel().getColumn(0).set
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        
        JButton btnVoltar = new JButton("Voltar");
        btnVoltar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new Relatorio().setVisible(true);
        		dispose();
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txEntrada, GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        							.addGap(18)
        							.addComponent(btnBuscar)))
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnCriar)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnApagar)
        					.addPreferredGap(ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
        					.addComponent(btnVoltar)
        					.addGap(29))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txEntrada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBuscar))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnCriar)
        				.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnApagar))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
        setSize(new DimensionUIResource(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        exibirTabela(pesquisar());
    }//GEN-LAST:event_btnBuscarActionPerformed
    private ArrayList<Doc> pesquisar(){
        ArrayList<Doc> resultados = new ArrayList<Doc>();
        for(Doc dados : tabela_default){
            if ( dados.getLinhaCompleta().toLowerCase().contains(txEntrada.getText().toLowerCase()) ){
                resultados.add(dados);
            }
        }
        return resultados;
    }
    private Nova_Tela selecionado;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        int index =(Integer) jTable1.getValueAt(row, 0);
        Doc d = DocControler.getById(index);
        System.out.println(index);
        System.out.println(d.getId());
        System.out.println(evt.getClickCount());
        if(evt.getClickCount() == 2){
            if(selecionado == null){
                selecionado = new Nova_Tela(d);
                selecionado.setVisible(true);
        }
        selecionado=null;
        dispose();
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        new Nova_Tela().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txEntrada;
}
