/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author cauaa7
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        tfNome_do_Arquivo.requestFocus();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lbTopo = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        btnCriar = new javax.swing.JButton();
        btnLer = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        pnPrincipal = new javax.swing.JPanel();
        lbNome_do_Arquivo = new javax.swing.JLabel();
        tfNome_do_Arquivo = new javax.swing.JTextField();
        lbConteudo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txConteudo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTopo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTopo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTopo.setText("NOME_PROJETO");
        lbTopo.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(lbTopo)
                .addGap(210, 210, 210))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTopo)
                .addGap(17, 17, 17))
        );

        btnCriar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnLer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLer.setText("Ler");
        btnLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBotoesLayout = new javax.swing.GroupLayout(pnBotoes);
        pnBotoes.setLayout(pnBotoesLayout);
        pnBotoesLayout.setHorizontalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnLer)
                .addGap(18, 18, 18)
                .addComponent(btnCriar)
                .addGap(27, 27, 27))
        );
        pnBotoesLayout.setVerticalGroup(
            pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBotoesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnLer)
                    .addComponent(btnEditar))
                .addGap(19, 19, 19))
        );

        lbNome_do_Arquivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNome_do_Arquivo.setText("Nome do Arquivo:");

        tfNome_do_Arquivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbConteudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbConteudo.setText("Conteúdo:");

        txConteudo.setColumns(20);
        txConteudo.setRows(5);
        jScrollPane1.setViewportView(txConteudo);

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(lbConteudo))
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lbNome_do_Arquivo)
                        .addGap(18, 18, 18)
                        .addComponent(tfNome_do_Arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome_do_Arquivo)
                    .addComponent(tfNome_do_Arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbConteudo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBotoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        FileWriter arq;
        try{
            arq = new FileWriter(new File(tfNome_do_Arquivo.getText() + ".txt"));
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.println(txConteudo.getText());
            gravarArq.close();
            arq.close();
            JOptionPane.showMessageDialog(null, "Arquivo " + tfNome_do_Arquivo.getText() + ".txt criado com sucesso.");
        } catch (IOException e){
            e.printStackTrace();
        }
        tfNome_do_Arquivo.setText("");
        txConteudo.setText("");
        tfNome_do_Arquivo.requestFocus();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerActionPerformed
        // TODO add your handling code here:
        String conteudo = "";
        try {
            FileReader arq = new FileReader(tfNome_do_Arquivo.getText() + ".txt");
            BufferedReader lerArq = new BufferedReader(arq);
            String linha = "";
            try {
                linha = lerArq.readLine();
                while(linha != null){
                    conteudo += linha + "\r\n";
                    linha = lerArq.readLine();
                }
                arq.close();
            } catch (IOException ex){
                JOptionPane.showMessageDialog(null, "Não foi possível ler o arquivo!");
            }
        } catch (FileNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado!");
        }
        lbConteudo.setText(tfNome_do_Arquivo.getText());
        tfNome_do_Arquivo.setText("");
        txConteudo.setText(conteudo);
        tfNome_do_Arquivo.requestFocus();
    }//GEN-LAST:event_btnLerActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        FileWriter arq;
        try{
            arq = new FileWriter(lbConteudo.getText() + ".txt");
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.println(txConteudo.getText());
            gravarArq.close();
            arq.close();
            JOptionPane.showMessageDialog(null, "Arquivo " + tfNome_do_Arquivo.getText() + ".txt editado com sucesso.");
        } catch (IOException e){
            e.printStackTrace();
        }
        lbConteudo.setText("Conteúdo:");
        tfNome_do_Arquivo.setText("");
        txConteudo.setText("");
        tfNome_do_Arquivo.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConteudo;
    private javax.swing.JLabel lbNome_do_Arquivo;
    private javax.swing.JLabel lbTopo;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField tfNome_do_Arquivo;
    private javax.swing.JTextArea txConteudo;
    // End of variables declaration//GEN-END:variables
}
